-- AlterTable
ALTER TABLE "Resume" ADD COLUMN     "photoUrl" TEXT NOT NULL DEFAULT '',
ALTER COLUMN "jobTitle" SET DEFAULT '',
ALTER COLUMN "firstName" SET DEFAULT '',
ALTER COLUMN "lastName" SET DEFAULT '',
ALTER COLUMN "email" SET DEFAULT '',
ALTER COLUMN "phone" SET DEFAULT '',
ALTER COLUMN "country" SET DEFAULT '',
ALTER COLUMN "city" SET DEFAULT '',
ALTER COLUMN "summary" SET DEFAULT '';
