import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { Suspense } from "react";
import { Toaster } from "react-hot-toast";

import { Navbar } from "@/components/navbar/Navbar";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "Resume Builder",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.png" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
      <body className="relative">
        <ThemeProvider defaultTheme="system" attribute="class" enableSystem>
          <TRPCReactProvider>
            <Navbar />
            <Toaster />
            <Suspense>{children}</Suspense>
          </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
