import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { notFound } from "next/navigation";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { setRequestLocale } from "next-intl/server";
import { Suspense } from "react";
import { Toaster } from "react-hot-toast";

import { Navbar } from "@/components/navbar/Navbar";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { routing } from "@/i18n/routing";
import { setDayjsLocale } from "@/lib/dayjs";
import { TRPCReactProvider } from "@/trpc/react";

export const metadata: Metadata = {
  title: "Resume Builder",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.png" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export function generateStaticParams() {
  return routing.locales
    .filter((locale) => locale === "en")
    .map((locale) => ({ locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<Props>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);
  setDayjsLocale(locale);

  return (
    <html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
      <body className="relative">
        <NextIntlClientProvider>
          <ThemeProvider defaultTheme="system" attribute="class" enableSystem>
            <TRPCReactProvider>
              <Navbar />
              <Toaster />
              <Suspense>{children}</Suspense>
            </TRPCReactProvider>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
